export type TalentType = "model" | "artist";
export type ArtistCategory = "makeup" | "hair" | "nails" | "lash" | "photographer" | "stylist";

export interface Talent {
  id: string;
  name: string;
  handle: string;
  type: TalentType;
  role: string;
  repScore: number;
  jobs: number;
  referrals: number;
  campaigns: number;
  rate: string;
  tier: "New" | "Active" | "Rising" | "Pro" | "Elite";
  available: boolean;
  verified: boolean;
  badges: string[];
  location: string;
  bio: string;
  modelStats?: {
    height: string;
    measurements: string;
    experience: string;
    aesthetic: string[];
  };
  artistCategory?: ArtistCategory;
  collaborations: { name: string; role: string; jobs: number }[];
  portfolio: string[];
}

export const ALL_TALENT: Talent[] = [
  {
    id: "m1",
    name: "Naledi Dube",
    handle: "@naledi.model",
    type: "model",
    role: "Commercial & Editorial",
    repScore: 92,
    jobs: 34,
    referrals: 12,
    campaigns: 8,
    rate: "R3,500/day",
    tier: "Elite",
    available: true,
    verified: true,
    badges: ["Editorial Pick", "Campaign Ready"],
    location: "Johannesburg",
    bio: "Commercial and editorial model with 4 years experience across print, digital and runway campaigns. Known for versatility and professional on-set presence.",
    modelStats: {
      height: "175cm",
      measurements: "85-60-90",
      experience: "4 years",
      aesthetic: ["Editorial", "Commercial", "Lifestyle"],
    },
    collaborations: [
      { name: "Lerato Dlamini", role: "MUA", jobs: 5 },
      { name: "Palesa Sithole", role: "Lash Tech", jobs: 3 },
    ],
    portfolio: [],
  },
  {
    id: "m2",
    name: "Zinhle Motha",
    handle: "@zinhle_zsa",
    type: "model",
    role: "Runway & Fashion",
    repScore: 88,
    jobs: 28,
    referrals: 9,
    campaigns: 6,
    rate: "R4,200/day",
    tier: "Pro",
    available: true,
    verified: true,
    badges: ["Runway Specialist"],
    location: "Cape Town",
    bio: "High-fashion runway model with a strong editorial eye. Experienced in luxury brand campaigns and international shows.",
    modelStats: {
      height: "179cm",
      measurements: "82-58-88",
      experience: "3 years",
      aesthetic: ["High Fashion", "Avant-garde", "Luxury"],
    },
    collaborations: [
      { name: "Ayanda Moyo", role: "Hair", jobs: 3 },
      { name: "Nomsa Khumalo", role: "MUA", jobs: 4 },
    ],
    portfolio: [],
  },
  {
    id: "m3",
    name: "Amara Osei",
    handle: "@amara.osei",
    type: "model",
    role: "Commercial & Lifestyle",
    repScore: 78,
    jobs: 19,
    referrals: 6,
    campaigns: 4,
    rate: "R2,800/day",
    tier: "Rising",
    available: false,
    verified: true,
    badges: ["Campaign Ready"],
    location: "Durban",
    bio: "Warm and approachable commercial model, perfect for lifestyle and wellness campaigns. Naturally vibrant energy on set.",
    modelStats: {
      height: "168cm",
      measurements: "88-65-95",
      experience: "2 years",
      aesthetic: ["Commercial", "Lifestyle", "Wellness"],
    },
    collaborations: [{ name: "Thandi Mokoena", role: "Nails", jobs: 2 }],
    portfolio: [],
  },
  {
    id: "m4",
    name: "Kefilwe Sithole",
    handle: "@kefilwe.s",
    type: "model",
    role: "New Face — Editorial",
    repScore: 62,
    jobs: 7,
    referrals: 2,
    campaigns: 1,
    rate: "R1,800/day",
    tier: "New",
    available: true,
    verified: false,
    badges: ["New Face"],
    location: "Pretoria",
    bio: "Striking new face with a natural editorial quality. Fast learner with a fresh perspective, eager to build her portfolio.",
    modelStats: {
      height: "172cm",
      measurements: "80-58-86",
      experience: "1 year",
      aesthetic: ["Editorial", "Emerging"],
    },
    collaborations: [],
    portfolio: [],
  },
  {
    id: "a1",
    name: "Lerato Dlamini",
    handle: "@lerato_mua",
    type: "artist",
    role: "Editorial MUA",
    repScore: 96,
    jobs: 52,
    referrals: 18,
    campaigns: 14,
    rate: "R2,200/day",
    tier: "Elite",
    available: true,
    verified: true,
    badges: ["Editorial Pick", "Top Rated"],
    location: "Johannesburg",
    bio: "Award-winning editorial makeup artist with a deep understanding of light, texture and skin. Works across film, fashion and advertising.",
    artistCategory: "makeup",
    collaborations: [
      { name: "Naledi Dube", role: "Model", jobs: 5 },
      { name: "Zinhle Motha", role: "Model", jobs: 2 },
    ],
    portfolio: [],
  },
  {
    id: "a2",
    name: "Thandi Mokoena",
    handle: "@thandi_nails",
    type: "artist",
    role: "Nail Art Specialist",
    repScore: 84,
    jobs: 41,
    referrals: 14,
    campaigns: 7,
    rate: "R1,400/day",
    tier: "Pro",
    available: true,
    verified: true,
    badges: ["Campaign Ready"],
    location: "Johannesburg",
    bio: "Creative nail technician specialising in custom nail art, gel, and press-on designs for editorial and events.",
    artistCategory: "nails",
    collaborations: [{ name: "Amara Osei", role: "Model", jobs: 2 }],
    portfolio: [],
  },
  {
    id: "a3",
    name: "Palesa Sithole",
    handle: "@palesa_lash",
    type: "artist",
    role: "Lash & Brow Expert",
    repScore: 79,
    jobs: 36,
    referrals: 11,
    campaigns: 5,
    rate: "R1,200/day",
    tier: "Pro",
    available: false,
    verified: true,
    badges: ["Specialist"],
    location: "Cape Town",
    bio: "Precision lash and brow specialist trusted by top models and editorial teams for flawless eye looks.",
    artistCategory: "lash",
    collaborations: [{ name: "Naledi Dube", role: "Model", jobs: 3 }],
    portfolio: [],
  },
  {
    id: "a4",
    name: "Zintle Xaba",
    handle: "@zintle_hair",
    type: "artist",
    role: "Natural Hair Specialist",
    repScore: 88,
    jobs: 44,
    referrals: 16,
    campaigns: 9,
    rate: "R1,800/day",
    tier: "Elite",
    available: true,
    verified: true,
    badges: ["Editorial Pick", "Natural Hair Expert"],
    location: "Johannesburg",
    bio: "Celebrated natural hair stylist with a signature approach to protective styles and textured hair for editorial and commercial work.",
    artistCategory: "hair",
    collaborations: [
      { name: "Naledi Dube", role: "Model", jobs: 4 },
      { name: "Kefilwe Sithole", role: "Model", jobs: 2 },
    ],
    portfolio: [],
  },
  {
    id: "a5",
    name: "Nomsa Khumalo",
    handle: "@nomsa_glam",
    type: "artist",
    role: "Glam & Events MUA",
    repScore: 72,
    jobs: 29,
    referrals: 8,
    campaigns: 3,
    rate: "R1,600/day",
    tier: "Rising",
    available: true,
    verified: false,
    badges: ["Rising Star"],
    location: "Durban",
    bio: "Glam-focused makeup artist with a strong portfolio in weddings, events and television. Known for flawless skin prep and lasting looks.",
    artistCategory: "makeup",
    collaborations: [{ name: "Zinhle Motha", role: "Model", jobs: 4 }],
    portfolio: [],
  },
  {
    id: "a6",
    name: "Sipho Dlamini",
    handle: "@sipho.photo",
    type: "artist",
    role: "Campaign Photographer",
    repScore: 91,
    jobs: 47,
    referrals: 20,
    campaigns: 12,
    rate: "R4,500/day",
    tier: "Elite",
    available: true,
    verified: true,
    badges: ["Editorial Pick", "Campaign Ready"],
    location: "Cape Town",
    bio: "Commercial and editorial photographer with a distinctive eye for light and narrative. Trusted by leading SA and international brands.",
    artistCategory: "photographer",
    collaborations: [
      { name: "Naledi Dube", role: "Model", jobs: 6 },
      { name: "Lerato Dlamini", role: "MUA", jobs: 4 },
    ],
    portfolio: [],
  },
  {
    id: "a7",
    name: "Ayanda Moyo",
    handle: "@ayanda_hair",
    type: "artist",
    role: "Colour Specialist",
    repScore: 85,
    jobs: 38,
    referrals: 13,
    campaigns: 8,
    rate: "R2,000/day",
    tier: "Pro",
    available: false,
    verified: true,
    badges: ["Colour Expert"],
    location: "Johannesburg",
    bio: "Hair colour specialist known for bold, fashion-forward colour work. From balayage to full creative transformations.",
    artistCategory: "hair",
    collaborations: [{ name: "Zinhle Motha", role: "Model", jobs: 3 }],
    portfolio: [],
  },
];

export const TEAM_ROLES = [
  { role: "Makeup Artist", cat: "makeup" },
  { role: "Model", cat: "model" },
  { role: "Photographer", cat: "photographer" },
  { role: "Hair Stylist", cat: "hair" },
  { role: "Nail Technician", cat: "nails" },
  { role: "Lash Tech", cat: "lash" },
  { role: "Stylist", cat: "stylist" },
];

export const TIER_COLORS: Record<string, string> = {
  New: "#8C7B72",
  Active: "#4A7AB8",
  Rising: "#B8893A",
  Pro: "#7A5AB8",
  Elite: "#C4526E",
};
