export type JobType = "Editorial" | "Commercial" | "TV/Film" | "Events" | "Bridal" | "Social Media";
export type JobRole = "MUA" | "Hair" | "Nails" | "Model" | "Photographer" | "Stylist" | "Lash & Brow";

export interface Job {
  id: string;
  title: string;
  client: string;
  clientType: "Brand" | "Agency" | "Private";
  brief: string;
  type: JobType;
  province: string;
  city: string;
  date: string;
  deadline: string;
  rate: string;
  rateNum: number;
  urgent: boolean;
  featured: boolean;
  roles: JobRole[];
  spotsTotal: number;
  spotsFilled: number;
  requirements: string[];
  tags: string[];
  posted: string;
}

export const JOB_BOARD: Job[] = [
  {
    id: "j1",
    title: "Luxury Skincare Campaign — Winter Edition",
    client: "Annique Beauty",
    clientType: "Brand",
    brief:
      "We're shooting our winter skincare campaign for print, digital, and in-store use. Looking for a skilled MUA with experience in glass-skin and dewy editorial finishes, plus an editorial model for hero and lifestyle shots. Two shoot days in our Johannesburg studio.",
    type: "Editorial",
    province: "GP",
    city: "Johannesburg",
    date: "June 2–3",
    deadline: "May 30",
    rate: "R3,500",
    rateNum: 3500,
    urgent: false,
    featured: true,
    roles: ["MUA", "Model"],
    spotsTotal: 2,
    spotsFilled: 0,
    requirements: [
      "Portfolio showing glass-skin or dewy editorial looks",
      "Full-day availability (8 am – 6 pm)",
      "Own professional kit required for MUA",
      "Experience with luxury brand campaigns preferred",
    ],
    tags: ["Skincare", "Editorial", "Studio"],
    posted: "2 days ago",
  },
  {
    id: "j2",
    title: "Summer Lookbook — Woolworths Fashion",
    client: "Woolworths Fashion",
    clientType: "Brand",
    brief:
      "Woolworths Fashion is casting for their summer lookbook. We need a female model (size 8–10) and a hairstylist comfortable with natural, effortless beach waves. Shoot takes place at a Cape Town studio with location elements at the Waterfront.",
    type: "Commercial",
    province: "WC",
    city: "Cape Town",
    date: "June 8",
    deadline: "June 1",
    rate: "R2,800",
    rateNum: 2800,
    urgent: true,
    featured: false,
    roles: ["Model", "Hair", "Stylist"],
    spotsTotal: 3,
    spotsFilled: 1,
    requirements: [
      "Model: female, size 8–10, height 170 cm+",
      "Hair: natural waves, effortless styling experience",
      "Stylist: commercial retail experience",
      "Cape Town based preferred",
    ],
    tags: ["Fashion", "Retail", "Beach"],
    posted: "1 day ago",
  },
  {
    id: "j3",
    title: "Cantu SA — Natural Haircare TV Commercial",
    client: "Cantu SA",
    clientType: "Brand",
    brief:
      "Cantu SA is producing a 30-second TV commercial celebrating natural African hair textures. We need a specialist natural hair stylist who can create stunning textured styles from 4a–4c curl patterns. Two shooting days in our Joburg production studio.",
    type: "TV/Film",
    province: "GP",
    city: "Johannesburg",
    date: "June 15–16",
    deadline: "June 8",
    rate: "R4,200",
    rateNum: 4200,
    urgent: true,
    featured: true,
    roles: ["Hair", "Model", "MUA"],
    spotsTotal: 3,
    spotsFilled: 1,
    requirements: [
      "Natural hair specialist — 4a–4c curl types",
      "On-set TV/film experience highly preferred",
      "Portfolio showcasing textured styles",
      "Both hair and MUA must be Joburg based or willing to travel",
    ],
    tags: ["Natural Hair", "TV", "Cantu"],
    posted: "3 days ago",
  },
  {
    id: "j4",
    title: "Afro-Futurist Editorial — Sunday Times Magazine",
    client: "Sunday Times Lifestyle",
    clientType: "Agency",
    brief:
      "Sunday Times Lifestyle Magazine is producing a 6-page afro-futurist fashion editorial. Think rich metallics, bold structural silhouettes, and dramatic beauty looks. We're looking for a creative MUA and editorial model with strong editorial posing.",
    type: "Editorial",
    province: "GP",
    city: "Johannesburg",
    date: "June 19",
    deadline: "June 12",
    rate: "R3,200",
    rateNum: 3200,
    urgent: false,
    featured: true,
    roles: ["MUA", "Model", "Stylist"],
    spotsTotal: 3,
    spotsFilled: 0,
    requirements: [
      "MUA: avant-garde and editorial experience essential",
      "Model: strong book, experience with editorial posing",
      "Stylist: conceptual fashion styling experience",
      "Full team must be available for a 10-hour shoot day",
    ],
    tags: ["Fashion", "Magazine", "Afro-Futurist", "Editorial"],
    posted: "5 hours ago",
  },
  {
    id: "j5",
    title: "Bridal Wellness Day — The Saxon Hotel",
    client: "The Saxon Hotel, Spa & Villas",
    clientType: "Private",
    brief:
      "A luxury bride-to-be event at the Saxon Hotel. Guests will receive bridal makeup trials, hair styling consultations, and nail services. Looking for three experienced beauty artists for a full Saturday. Relaxed, warm, and elegant vibe.",
    type: "Bridal",
    province: "GP",
    city: "Sandton",
    date: "June 21",
    deadline: "June 14",
    rate: "R1,800",
    rateNum: 1800,
    urgent: false,
    featured: false,
    roles: ["MUA", "Hair", "Nails"],
    spotsTotal: 3,
    spotsFilled: 1,
    requirements: [
      "MUA: bridal portfolio required",
      "Hair: updo and blowdry experience essential",
      "Nails: bridal nail art and gel extension experience",
      "Warm, professional client manner required",
    ],
    tags: ["Bridal", "Luxury", "Hotel"],
    posted: "1 day ago",
  },
  {
    id: "j6",
    title: "Superbalist — Campaign Content Creator",
    client: "Superbalist",
    clientType: "Brand",
    brief:
      "Superbalist is producing always-on social content for Instagram and TikTok. We need two female models comfortable on camera who can guide their own movement and expression for short-form video. Shot at our Cape Town studio over two days.",
    type: "Social Media",
    province: "WC",
    city: "Cape Town",
    date: "June 25–26",
    deadline: "June 17",
    rate: "R2,400",
    rateNum: 2400,
    urgent: false,
    featured: false,
    roles: ["Model", "MUA"],
    spotsTotal: 2,
    spotsFilled: 0,
    requirements: [
      "Female models, diverse sizes and looks encouraged",
      "Comfortable with video — TikTok-style performance",
      "MUA: natural and quick-change looks",
      "Cape Town based strongly preferred",
    ],
    tags: ["Social Media", "Fashion", "TikTok"],
    posted: "4 days ago",
  },
  {
    id: "j7",
    title: "Durban Bridal Expo — Live Demos",
    client: "SA Wedding Expo",
    clientType: "Agency",
    brief:
      "SA Wedding Expo is hosting the annual Durban Bridal Expo. We need three talented beauty artists to perform live demonstrations of bridal looks throughout the day. Great exposure to hundreds of engaged couples and industry professionals.",
    type: "Events",
    province: "KZN",
    city: "Durban",
    date: "June 28",
    deadline: "June 20",
    rate: "R1,500",
    rateNum: 1500,
    urgent: false,
    featured: false,
    roles: ["MUA", "Hair", "Nails"],
    spotsTotal: 3,
    spotsFilled: 2,
    requirements: [
      "Must have bridal hair or makeup experience",
      "Comfortable performing in front of live audiences",
      "Own full kit required",
      "Durban/KZN based preferred",
    ],
    tags: ["Bridal", "Expo", "Live Demo"],
    posted: "6 days ago",
  },
  {
    id: "j8",
    title: "Lash Extension Masterclass Model",
    client: "GlamAcademy SA",
    clientType: "Agency",
    brief:
      "GlamAcademy SA is running a certified lash extension masterclass in Pretoria. We need 4 models to serve as live training subjects for up to 8 students. You'll receive a free set of extensions plus a cash rate.",
    type: "Events",
    province: "GP",
    city: "Pretoria",
    date: "July 2",
    deadline: "June 25",
    rate: "R600",
    rateNum: 600,
    urgent: false,
    featured: false,
    roles: ["Model", "Lash & Brow"],
    spotsTotal: 4,
    spotsFilled: 1,
    requirements: [
      "No lash extensions currently applied",
      "No known adhesive allergies",
      "Comfortable with extended eye-closed periods",
      "Free extensions provided as additional compensation",
    ],
    tags: ["Lash", "Training", "Model"],
    posted: "1 week ago",
  },
  {
    id: "j9",
    title: "Kiehl's SA — Micro-influencer Campaign",
    client: "Kiehl's South Africa",
    clientType: "Brand",
    brief:
      "Kiehl's SA is launching their new Ultra Facial Cream with a micro-influencer content campaign. We need two female models for a clean, minimalist beauty shoot — think serene morning skincare ritual. Shot in a beautiful Joburg home studio.",
    type: "Commercial",
    province: "GP",
    city: "Johannesburg",
    date: "July 5",
    deadline: "June 28",
    rate: "R2,600",
    rateNum: 2600,
    urgent: false,
    featured: true,
    roles: ["Model", "MUA", "Photographer"],
    spotsTotal: 3,
    spotsFilled: 0,
    requirements: [
      "Models: clean, natural skin — no heavy tattoos visible on face/neck",
      "MUA: expertise in no-makeup makeup and skin prep",
      "Photographer: lifestyle and beauty work in portfolio",
      "All genders encouraged to apply",
    ],
    tags: ["Skincare", "Lifestyle", "Clean Beauty"],
    posted: "2 days ago",
  },
  {
    id: "j10",
    title: "Music Video — Afrobeats Artist",
    client: "Private Client (via GlamNet)",
    clientType: "Private",
    brief:
      "Rising Afrobeats artist based in Joburg is shooting a high-energy music video. Looking for a bold, creative MUA for editorial glam looks and two female models/dancers comfortable on set. Full day shoot. Fun, high-energy environment!",
    type: "TV/Film",
    province: "GP",
    city: "Johannesburg",
    date: "July 8",
    deadline: "July 1",
    rate: "R2,000",
    rateNum: 2000,
    urgent: false,
    featured: false,
    roles: ["MUA", "Model"],
    spotsTotal: 3,
    spotsFilled: 0,
    requirements: [
      "MUA: bold, editorial, stage/video looks portfolio",
      "Models: comfortable with dancing and movement on camera",
      "High energy, fun working environment",
      "All looks provided by artist's stylist",
    ],
    tags: ["Music Video", "Afrobeats", "Performance"],
    posted: "3 days ago",
  },
];

export const JOB_TYPES: { id: string; label: string }[] = [
  { id: "all", label: "All" },
  { id: "Editorial", label: "Editorial" },
  { id: "Commercial", label: "Commercial" },
  { id: "TV/Film", label: "TV / Film" },
  { id: "Events", label: "Events" },
  { id: "Bridal", label: "Bridal" },
  { id: "Social Media", label: "Social" },
];
