import type { Artist, BookingRequest, Campaign, Applicant } from './types';

export const ARTISTS: Artist[] = [
  {
    id: '1',
    name: 'Naledi Dlamini',
    specialty: 'Bridal Makeup',
    location: 'Cape Town',
    dayRate: 2800,
    rating: 4.9,
    reviews: 127,
    available: true,
    skills: ['Bridal', 'Editorial', 'Airbrush'],
    bio: 'Cape Town-based bridal makeup artist with 8 years experience. Known for soft, luminous looks that photograph beautifully and last all day.',
    seed: '1',
  },
  {
    id: '2',
    name: 'Ayasha Khoza',
    specialty: 'Hair Styling',
    location: 'Johannesburg',
    dayRate: 1800,
    rating: 4.7,
    reviews: 89,
    available: true,
    skills: ['Natural Hair', 'Braids', 'Blowouts'],
    bio: 'Specialising in natural African hair with a love for protective styles and textures that celebrate heritage.',
    seed: '2',
  },
  {
    id: '3',
    name: 'Priya Naidoo',
    specialty: 'Nail Art',
    location: 'Durban',
    dayRate: 1200,
    rating: 4.8,
    reviews: 203,
    available: false,
    skills: ['Gel', 'Acrylic', 'Nail Art', 'Extensions'],
    bio: "Durban's most-booked nail artist. Intricate designs from minimalist to maximalist. Two weeks booked out.",
    seed: '3',
  },
  {
    id: '4',
    name: 'Zanele Mokoena',
    specialty: 'Editorial Makeup',
    location: 'Pretoria',
    dayRate: 2200,
    rating: 4.6,
    reviews: 64,
    available: true,
    skills: ['Editorial', 'SFX', 'Contouring', 'Body Art'],
    bio: 'Editorial and commercial makeup artist. Shot for Vogue Africa, Elle, and multiple national ad campaigns.',
    seed: '4',
  },
  {
    id: '5',
    name: 'Lerato Sithole',
    specialty: 'Full Glam',
    location: 'Soweto',
    dayRate: 2500,
    rating: 4.9,
    reviews: 156,
    available: true,
    skills: ['Full Glam', 'Wedding', 'Photoshoot', 'Film & TV'],
    bio: 'Full-service glam artist for weddings, events, and film. Dedicated kit, will travel.',
    seed: '5',
  },
  {
    id: '6',
    name: 'Thandi Mthembu',
    specialty: 'Natural Hair',
    location: 'Sandton',
    dayRate: 1600,
    rating: 4.5,
    reviews: 41,
    available: true,
    skills: ['Locs', 'Twists', 'Protective Styles', 'Faux Locs'],
    bio: 'Natural hair specialist with 6 years experience in locs, twists, and protective styling.',
    seed: '6',
  },
];

export const BOOKING_REQUESTS: BookingRequest[] = [
  {
    id: 'r1',
    clientName: 'Amara Osei',
    service: 'Bridal Makeup',
    date: '14 Jul 2026',
    time: '08:00',
    location: 'Vineyard Hotel, Cape Town',
    budget: 2800,
    status: 'pending',
  },
  {
    id: 'r2',
    clientName: 'Fatima Patel',
    service: 'Editorial Look',
    date: '16 Jul 2026',
    time: '10:00',
    location: 'Studio 9, De Waterkant',
    budget: 2200,
    status: 'pending',
  },
  {
    id: 'r3',
    clientName: 'Mia van der Berg',
    service: 'Glam Makeup',
    date: '20 Jul 2026',
    time: '15:00',
    location: "Client's home, Constantia",
    budget: 1800,
    status: 'pending',
  },
];

export const CAMPAIGNS: Campaign[] = [
  {
    id: 'c1',
    title: 'Revlon Summer Glow',
    role: 'Makeup Artist',
    budget: 45000,
    deadline: '10 Aug 2026',
    applicants: 12,
    status: 'active',
  },
  {
    id: 'c2',
    title: 'Vitaderm Vitamin Ad Shoot',
    role: 'Hair Stylist',
    budget: 28000,
    deadline: '25 Jul 2026',
    applicants: 7,
    status: 'active',
  },
  {
    id: 'c3',
    title: 'SAFW Fashion Week Prep',
    role: 'Multiple Roles',
    budget: 120000,
    deadline: '2 Sep 2026',
    applicants: 23,
    status: 'active',
  },
];

export const APPLICANTS: Applicant[] = [
  {
    id: 'a1',
    name: 'Nomsa Vilakazi',
    specialty: 'Editorial Makeup',
    rating: 4.8,
    dayRate: 2400,
    location: 'Johannesburg',
    seed: 'a1',
  },
  {
    id: 'a2',
    name: 'Kezia Baloyi',
    specialty: 'Bridal Makeup',
    rating: 4.9,
    dayRate: 2800,
    location: 'Cape Town',
    seed: 'a2',
  },
  {
    id: 'a3',
    name: 'Rania Abdi',
    specialty: 'Commercial Makeup',
    rating: 4.6,
    dayRate: 2000,
    location: 'Pretoria',
    seed: 'a3',
  },
  {
    id: 'a4',
    name: 'Sindi Dube',
    specialty: 'SFX & Glam',
    rating: 4.7,
    dayRate: 2200,
    location: 'Durban',
    seed: 'a4',
  },
];
